In [2]:
import pandas as pd
import numpy as np

In [3]:
pokemon = pd.read_csv("pokemon.csv")

In [4]:
pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [5]:
pokemon.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [6]:
pokemon.shape

(800, 13)

In [7]:
pokemon.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [8]:
pokemon.HP.value_counts().sort_values()

1      1
28     1
10     1
42     1
37     1
      ..
75    43
65    46
70    57
50    63
60    67
Name: HP, Length: 94, dtype: int64

In [9]:
pokemon.HP.describe()

count    800.000000
mean      69.258750
std       25.534669
min        1.000000
25%       50.000000
50%       65.000000
75%       80.000000
max      255.000000
Name: HP, dtype: float64

In [13]:
pokemon["Type 1"].value_counts()

Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Rock         44
Electric     44
Ghost        32
Dragon       32
Ground       32
Dark         31
Poison       28
Fighting     27
Steel        27
Ice          24
Fairy        17
Flying        4
Name: Type 1, dtype: int64

In [14]:
pokemon["Type 2"].value_counts()

Flying      97
Ground      35
Poison      34
Psychic     33
Fighting    26
Grass       25
Fairy       23
Steel       22
Dark        20
Dragon      18
Water       14
Rock        14
Ghost       14
Ice         14
Fire        12
Electric     6
Normal       4
Bug          3
Name: Type 2, dtype: int64

Most pokemons are Water and Flying pokemons.

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

# Create some Filters with Boolean Series

## Attack more then 75 (more_attack)

In [11]:
more_attack = pokemon["Attack"] >= 75

In [62]:
more_attack

0      False
1      False
2       True
3       True
4      False
       ...
795     True
796     True
797     True
798     True
799     True
Name: Attack, Length: 800, dtype: bool

In [66]:
more_attack.shape

(800,)

## Speed more then 75 (more_speed)

In [15]:
more_speed = pokemon["Speed"] >= 75

In [67]:
more_speed.shape

(800,)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

In [71]:
print("--"*50)

----------------------------------------------------------------------------------------------------

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

# Question 1:

# How many pokemons has more attack than 75 and more speed then 75?

In [84]:
pokemon_more_attack_speed = pokemon[more_attack & more_speed]

In [85]:
pokemon_more_attack_speed

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True

In [86]:
pokemon_more_attack_speed.shape

(225, 13)

## 225 pokemons are more then 75 regarding attack and speed.

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

# Question 2:

# How many water pokemons has more attack than 75 and more speed then 75?

In [87]:
water_pokemons = pokemon["Type 1"] == "Water"

In [88]:
water_pokemons.shape

(800,)

In [89]:
water_pokemon_more_attack_speed = pokemon[more_attack & more_speed & water_pokemons]

In [76]:
water_pokemons

0      False
1      False
2      False
3      False
4      False
       ...
795    False
796    False
797    False
798    False
799    False
Name: Type 1, Length: 800, dtype: bool

In [91]:
water_pokemon_more_attack_speed.shape

(23, 13)

In [90]:
water_pokemon_more_attack_speed

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
60,55,Golduck,Water,NaN,500,80,82,78,95,80,85,1,False
107,99,Kingler,Water,NaN,475,55,130,115,50,50,75,1,False
130,121,Starmie,Water,Psychic,520,60,75,85,100,85,115,1,False
140,130,Gyarados,Water,Flying,540,95,125,79,60,100,81,1,False
141,130,GyaradosMega Gyarados,Water,Dark,640,95,155,109,70,130,81,1,False
174,160,Feraligatr,Water,NaN,530,85,105,100,79,83,78,2,False
227,211,Qwilfish,Water,Poison,430,65,95,75,55,55,85,2,False
249,230,Kingdra,Water,Dragon,540,75,95,95,95,95,85,2,False
264,245,Suicune,Water,NaN,580,100,75,115,90,115,85,2,True
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False
349,319,SharpedoMega Sharpedo,Water,Dark,560,70,140,70,110,65,105,3,False
421,382,Kyogre,Water,NaN,670,100,100,90,150,140,90,3,True
422,382,KyogrePrimal Kyogre,Water,NaN,770,100,150,90,180,160,90,3,True
466,419,Floatzel,Water,NaN,495,85,105,55,85,50,115,4,False
541,484,Palkia,Water,Dragon,680,90,120,100,150,120,100,4,True
547,489,Phione,Water,NaN,480,80,80,80,80,80,80,4,False
548,490,Manaphy,Water,NaN,600,100,100,100,100,100,100,4,False
575,516,Simipour,Water,NaN,498,75,98,63,98,63,101,5,False
610,550,Basculin,Water,NaN,460,70,92,65,80,55,98,5,False
642,581,Swanna,Water,Flying,473,75,87,63,87,63,98,5,False
726,658,Greninja,Water,Dark,530,72,95,67,103,71,122,6,False

## 23 water pokemons are more then 75 regarding attack and speed.

In [92]:
print("--"*50)

----------------------------------------------------------------------------------------------------

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

# Question 3:

# How many Flying pokemons has more attack than 75 and more speed then 75?

In [93]:
flying_pokemon = pokemon["Type 2"] == "Flying"

In [94]:
flying_pokemon.shape

(800,)

In [95]:
flying_pokemon_more_attack_speed = pokemon[more_speed & more_attack & flying_pokemon]

In [97]:
flying_pokemon_more_attack_speed.shape

(47, 13)

In [96]:
flying_pokemon_more_attack_speed

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
27,22,Fearow,Normal,Flying,442,65,90,65,61,61,100,1,False
47,42,Golbat,Poison,Flying,455,75,80,70,65,75,90,1,False
91,84,Doduo,Normal,Flying,310,35,85,45,35,35,75,1,False
92,85,Dodrio,Normal,Flying,460,60,110,70,60,60,100,1,False
132,123,Scyther,Bug,Flying,500,70,110,80,55,80,105,1,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
140,130,Gyarados,Water,Flying,540,95,125,79,60,100,81,1,False
153,142,Aerodactyl,Rock,Flying,515,80,105,65,60,75,130,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
156,144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,True
157,145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,True
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
161,149,Dragonite,Dragon,Flying,600,91,134,95,100,100,80,1,False
183,169,Crobat,Poison,Flying,535,85,90,80,70,80,130,2,False
192,178,Xatu,Psychic,Flying,470,65,75,70,95,70,95,2,False
213,198,Murkrow,Dark,Flying,405,60,85,42,85,42,91,2,False
222,207,Gligar,Ground,Flying,430,65,75,105,35,65,85,2,False
269,249,Lugia,Psychic,Flying,680,106,90,130,90,154,110,2,True
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
300,277,Swellow,Normal,Flying,430,60,85,60,50,50,125,3,False
315,291,Ninjask,Bug,Flying,456,61,90,45,50,50,160,3,False
408,373,Salamence,Dragon,Flying,600,95,135,80,110,80,100,3,False
409,373,SalamenceMega Salamence,Dragon,Flying,700,95,145,130,120,90,120,3,False
425,384,Rayquaza,Dragon,Flying,680,105,150,90,150,90,95,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
442,397,Staravia,Normal,Flying,340,55,75,50,40,40,80,4,False
443,398,Staraptor,Normal,Flying,485,85,120,70,50,60,100,4,False
473,426,Drifblim,Ghost,Flying,498,150,80,44,90,54,80,4,False
520,469,Yanmega,Bug,Flying,515,86,76,86,116,56,95,4,False
523,472,Gliscor,Ground,Flying,510,75,95,125,45,75,95,4,False
551,492,ShayminSky Forme,Grass,Flying,600,100,103,75,120,75,127,4,True
580,521,Unfezant,Normal,Flying,488,80,115,80,65,55,93,5,False
628,567,Archeops,Rock,Flying,567,75,140,65,112,65,110,5,False
642,581,Swanna,Water,Flying,473,75,87,63,87,63,98,5,False
648,587,Emolga,Electric,Flying,428,55,75,60,75,60,103,5,False
689,628,Braviary,Normal,Flying,510,100,123,75,57,75,80,5,False
704,642,ThundurusIncarnate Forme,Electric,Flying,580,79,115,70,125,80,111,5,True
705,642,ThundurusTherian Forme,Electric,Flying,580,79,105,70,145,80,101,5,True
708,645,LandorusIncarnate Forme,Ground,Flying,600,89,125,90,115,80,101,5,True
709,645,LandorusTherian Forme,Ground,Flying,600,89,145,90,105,80,91,5,True
731,663,Talonflame,Fire,Flying,499,78,81,71,74,69,126,6,False
771,701,Hawlucha,Fighting,Flying,500,78,92,75,74,63,118,6,False
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True

## 47 flying pokemons are more then 75 regarding attack and speed.

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

# Question 4:

# How many pokemons Total has more than 700 ?

In [98]:
more_total_700 = pokemon["Total"] >= 700

In [104]:
pokemon_more_total_700 = pokemon [more_total_700]
pokemon_more_total_700

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True
268,248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False
409,373,SalamenceMega Salamence,Dragon,Flying,700,95,145,130,120,90,120,3,False
413,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False
418,380,LatiasMega Latias,Dragon,Psychic,700,80,100,120,140,150,110,3,True
420,381,LatiosMega Latios,Dragon,Psychic,700,80,130,100,160,120,110,3,True
422,382,KyogrePrimal Kyogre,Water,NaN,770,100,150,90,180,160,90,3,True
424,383,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
494,445,GarchompMega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,4,False
552,493,Arceus,Normal,NaN,720,120,120,120,120,120,120,4,True
711,646,KyuremBlack Kyurem,Dragon,Ice,700,125,170,100,120,90,95,5,True
712,646,KyuremWhite Kyurem,Dragon,Ice,700,125,120,90,170,100,95,5,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True

In [105]:
pokemon_more_total_700["Type 1"].value_counts()

Dragon     7
Psychic    2
Rock       2
Water      1
Steel      1
Ground     1
Normal     1
Name: Type 1, dtype: int64